### PR TITLE
updating the issue creds proposal attachment format

### PR DESCRIPTION
**Pull request by supersonicwisd1**

### CODE REVIEW

**Comment by gvelez17** [comment]
hm i don't see anything in this PR that actually changes the presentation to be VC compatible

@ianco if you have time, we might merge this into our branch for better visibility, but i'm not sure this fully captures it

**Comment by gvelez17** [comment]
@supersonicwisd1 are you able to run the demo with this branch, and if so can you provide here in the PR the json of the presentation that is returned?  that would be super helpful

**Review by gvelez17 — APPROVED** [review]
approved for merge, but also would like to wait for Ian's comment if he has time

**Comment by supersonicwisd1** [comment]
> @supersonicwisd1 are you able to run the demo with this branch, and if so can you provide here in the PR the json of the presentation that is returned? that would be super helpful


Here is Json of the output
"cred_preview": {
        "@type": "https://didcomm.org/issue-credential/2.0/credential-preview",
        "attributes": [
            {
                "name": "name",
                "value": "Alice Smith"
            },
            {
                "name": "date",
                "value": "2018-05-28"
            },
            {
                "name": "degree",
                "value": "Maths"
            },
            {
                "name": "birthdate_dateint",
                "value": "20000308"
            },
            {
                "name": "timestamp",
                "value": "1709934080"
            }
        ]
    },
    "cred_proposal": {
        "@type": "https://didcomm.org/issue-credential/2.0/propose-credential",
        "@id": "a40ccb4b-6366-4ad7-bd86-10d96f7487f6",
        "comment": "Offer on cred def id U4ZoTWgVszxC8Bx3iFfPbk:3:CL:236034:faber.agent.degree_schema",
        "credential_preview": {
            "@type": "https://didcomm.org/issue-credential/2.0/credential-preview",
            "attributes": [
                {
                    "name": "name",
                    "value": "Alice Smith"
                },
                {
                    "name": "date",
                    "value": "2018-05-28"
                },
                {
                    "name": "degree",
                    "value": "Maths"
                },
                {
                    "name": "birthdate_dateint",
                    "value": "20000308"
                },
                {
                    "name": "timestamp",
                    "value": "1709934080"
                }
            ]
        },
        "formats": [
            {
                "attach_id": "vc_di",
                "format": "didcomm/w3c-di-vc@v0.1"
            }
        ],
        "filters~attach": [
            {
                "@id": "vc_di",
                "mime-type": "application/json",
                "data": {
                    "base64": "eyJjcmVkX2RlZl9pZCI6ICJVNFpvVFdnVnN6eEM4QngzaUZmUGJrOjM6Q0w6MjM2MDM0OmZhYmVyLmFnZW50LmRlZ3JlZV9zY2hlbWEifQ=="
                }
            }
        ]
    },
    "cred_offer": {
        "@type": "https://didcomm.org/issue-credential/2.0/offer-credential",
        "@id": "137cd9a7-060d-493d-a08c-44d480c1a3db",
        "~thread": {},
        "comment": "Offer on cred def id U4ZoTWgVszxC8Bx3iFfPbk:3:CL:236034:faber.agent.degree_schema",
        "credential_preview": {
            "@type": "https://didcomm.org/issue-credential/2.0/credential-preview",
            "attributes": [
                {
                    "name": "name",
                    "value": "Alice Smith"
                },
                {
                    "name": "date",
                    "value": "2018-05-28"
                },
                {
                    "name": "degree",
                    "value": "Maths"
                },
                {
                    "name": "birthdate_dateint",
                    "value": "20000308"
                },
                {
                    "name": "timestamp",
                    "value": "1709934080"
                }
            ]
        },
        "formats": [
            {
                "attach_id": "vc_di",
                "format": "didcomm/w3c-di-vc-offer@v0.1"
            }
        ],
        "offers~attach": [
            {
                "@id": "vc_di",
                "mime-type": "application/json",
                "data": {

**Pull request merged**
